---

local_src_dir: "{{ user.home }}/Downloads/source"
local_bin_dir: "{{ user.home }}/bin"
temp_dir: /tmp

gnupg:
  enable_agent: False
  emulate_ssh: False

dotfiles:
  url: git@github.com:b08x/dotfiles.git
  branch: Main
  destination: "{{ user.home }}/Workspace/dotfiles"
  rcup_flags: -fx README.md

user:
  name: b08x
  uid: 1000
  gid: 1000
  group: b08x
  shell: /bin/bash
  email: rwpannick@gmail.com
  home: /home/b08x
  password: $1$ynx7axf8$D/jA4ELwCCtvToD9tcmDq.

domain: simulation46a.org
nameserver01: 192.168.36.1
