---

local_src_dir: "{{ user.home }}/Workspace/source"
local_bin_dir: "{{ user.home }}/.local/bin"
themes_dir: "{{ user.home }}/.themes"
icons_dir: "{{ user.home }}/.icons"

temp_dir: /tmp

gnupg:
  enable_agent: False
  emulate_ssh: False

dotfiles:
  url: git@github.com:b08x/dots.git
  branch: main

user_groups:
  - name: home
    gid: 1041

user:
  name: b08x
  home: /home/b08x
  sshdir: /home/b08x/.ssh
  uid: 1000
  gid: 1000
  primary_group: b08x
  secondary_groups: "wheel,network,input,home,storage,video,users,audio"
  shell: /bin/zsh
  email: rwpannick@gmail.com
  password: $1$ynx7axf8$D/jA4ELwCCtvToD9tcmDq.
