---

local_src_dir: "{{ user.home }}/Downloads/source"
local_bin_dir: "{{ user.home }}/bin"
temp_dir: /tmp

gnupg:
  enable_agent: False
  emulate_ssh: False

dotfiles:
  url: git@github.com:b08x/dotfiles.git
  branch: Main
  destination: "{{ user.home }}/Workspace/dotfiles"
  rcup_flags: -fx README.md

unix_groups:
  - name: home
    gid: 1040

unix_users:
  - name: b08x
    uid: 1000
    primary_group: b08x
    secondary_groups: "wheel,network,docker,input,audio"
    shell: /bin/bash
    email: rwpannick@gmail.com
    password: $1$ynx7axf8$D/jA4ELwCCtvToD9tcmDq.

domain: simulation46a.org
nameserver01: 192.168.36.1
