---

local_src_dir: "{{ user.home }}/Workspace/source"
local_bin_dir: "{{ user.home }}/bin"
themes_dir: "{{ user.home }}/.themes"
icons_dir: "{{ user.home }}/.icons"

temp_dir: /tmp

gnupg:
  enable_agent: False
  emulate_ssh: False

dotfiles:
  url: git@github.com:b08x/dotfiles.git
  branch: main
  destination: "{{ user.home }}/Workspace/dotfiles"
  rcup_flags: -fx README.md

user_groups:
  - name: home
    gid: 1041

user:
  name: b08x
  home: /home/b08x
  sshdir: /home/b08x/.ssh
  uid: 1000
  gid: 995
  primary_group: audio
  secondary_groups: "wheel,network,input,home,storage,video"
  shell: /bin/zsh
  email: rwpannick@gmail.com
  password: $1$ynx7axf8$D/jA4ELwCCtvToD9tcmDq.

font: Hack Nerd Font Regular

git_name: "{{ user.name }}"
git_mail: "{{ user.email }}"
