---

local_src_dir: "{{ unix_admin.home }}/Workspace/source"
local_bin_dir: "{{ unix_admin.home }}/bin"
themes_dir: "{{ unix_admin.home }}/.themes"
icons_dir: "{{ unix_admin.home }}/.icons"

temp_dir: /tmp

gnupg:
  enable_agent: False
  emulate_ssh: False

dotfiles:
  url: git@github.com:b08x/dotfiles.git
  branch: main
  destination: "{{ unix_admin.home }}/Workspace/dotfiles"
  rcup_flags: -fx README.md

user_groups:
  - name: home
    gid: 1041

system_groups:
  - lp
  - storage

unix_admin:
  name: b08x
  home: /home/b08x
  sshdir: /home/b08x/.ssh
  uid: 1000
  gid: 995
  primary_group: audio
  secondary_groups: "wheel,network,input,home,storage"
  shell: /bin/bash
  email: rwpannick@gmail.com
  password: $1$ynx7axf8$D/jA4ELwCCtvToD9tcmDq.

sudoname: "{{ unix_admin.name }}"

font: Hack Nerd Font Regular
git_name: b08x
git_mail: rwpannick@gmail.com
