---

- name: reload mako
  shell: makoctl reload
  when: ansible_virtualization_role == "host"
  ignore_errors: yes
  become: yes
  become_user: "{{ user.name }}"

- name: reload user systemd
  systemd: daemon_reload=yes scope=user
  become: yes
  become_user: "{{ user.name }}"

- name: enable ly service
  systemd: enabled=yes name=ly
  ignore_errors: true
#
# - name: enable guake service
#   systemd: name=guake scope=user state=started enabled=true
