---

- name: setup
  gather_facts: yes
  hosts: localhost

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: ['facts']

#  roles:
#     - { role: network, tags: ['network'] }
#     - { role: system, tags: ['system'] }
#     - { role: dotfiles, tags: ['dotfiles'] }
