---

- name: setup
  gather_facts: yes
  hosts: bender

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: ['facts']

 roles:
    - { role: system, tags: ['system'] }
    - { role: dotfiles, tags: ['dotfiles'] }
