---

- name: setup
  gather_facts: yes
  hosts: ninjabot

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_mounts
      tags: ['facts']

    # - name: register filesystem types
    #   ansible.builtin.setup:
    #     filter: ansible_mounts
    #   register: fstypes
    #   tags: ['fstypes']

    # - name: gather list of installed packages
    #   shell: "pamac list --installed | awk '{print $1}'"
    #   args:
    #     executable: /bin/bash
    #   become: yes
    #   become_user: "{{ unix_admin.name }}"
    #   register: installed_packages
    #   tags: ['packages']
    #
    - name: Print all available facts
      ansible.builtin.debug:
        var: initial_install
      tags: ['test']

  roles:
     - { role: network, tags: ['network'] }
     - { role: system, tags: ['system'] }
     - { role: ui, tags: ['ui'] }
     - { role: studio, tags: ['studio'] }
     - { role: workstation, tags: ['workstation'] }
     - { role: dotfiles, tags: ['dotfiles'] }
