---

- name: setup
  gather_facts: yes
  hosts: laptops

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: ['facts']

  roles:
     - { role: network, tags: ['network'] }
     - { role: system, tags: ['system'] }
     - { role: ui, tags: ['ui'] }
     - { role: studio, tags: ['studio'] }
     - { role: workstation, tags: ['workstation'] }
     - { role: dotfiles, tags: ['dotfiles'] }
