---

- name: setup
  gather_facts: yes
  hosts: all

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: ['facts']

    - name: reboot to enable uinput perms
      command: shutdown -r now
      when: reboot is defined


  roles:
     - { role: network, tags: ['network'] }
     - { role: common, tags: ['common'] }
     - { role: system, tags: ['system'] }
     - { role: soundbot, tags: ['soundbot'] }
     - { role: workstation, tags: ['workstation'] }
     - { role: ui, tags: ['ui'] }
