---

- name: setup
  hosts: soundbots
  gather_facts: yes
  collections:
    - community.general

  roles:
    - { role: network, tags: ['network'] }
    - { role: system, tags: ['system'] }
  #   - { role: dotfiles, tags: ['dotfiles'] }
  #   - { role: workstation, tags: ['workstation'] }
  #   - { role: rvm, tags: ['rvm'] }
  #   - { role: studio, tags: ['studio'] }
