---

- name: do stuff
  gather_facts: yes
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: ['facts']

  roles:
  - { role: network, tags: ['network'] }
  - { role: system, tags: ['system'] }
  - { role: studio, tags: ['studio'] }
