---

- name: setup
  gather_facts: yes
  hosts: soundbots
  collections:
    - community.general

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

  roles:
     - { role: network, tags: ['network'] }
     - { role: system, tags: ['system'] }
     - { role: studio, tags: ['studio'] }
     - { role: workstation, tags: ['workstation'] }
