---
configure_network: false
enable_zram_swap: false
network_interface: "e*"
dns_servers: []

# for headless hosts, at least one terminal emulator needs to be installed
#- xterm
#- htop
common_pkgs:
  - lnav
  - zsh-theme-powerlevel10k-git
  - oh-my-zsh
  - fzf
  - bat
  - exa
  - htop
  - iftop
  - iotop
  - net-tools
  - python-pip
  - wol
