---

- block:

  - name: clone dotfiles
    git: >
      repo={{ dotfiles.url }}
      version={{ dotfiles.branch }}
      dest={{ dotfiles.destination }}
      accept_hostkey=yes
      update=yes
      force=yes
    when: dotfiles is defined

  - name: push rcrc
    template: >
      src=rcrc.j2
      dest="{{ unix_admin.home}}/.rcrc"
      mode=0644
      backup=yes
    when: dotfiles is defined

  - name: Install profile
    command: rcup -v -d {{ dotfiles.destination}} {{ dotfiles.rcup_flags }}
    when: dotfiles is defined
    tags: ['profile']

  become: yes
  become_user: "{{ unix_admin.name }}"

- include: rcup.yml
  tags: ['rcm']
