---

- name: install rcm
  aur: name= {{ item }} user=aurman
  with_items:
    - rcm
  tags: [rcm]

- block:

  - name: Clone user dotfiles
    git: repo={{ dotfiles.url }} dest={{ dotfiles.destination }} accept_hostkey=yes update=no version={{ dotfiles.branch }}
    when: dotfiles is defined

    # TODO: add condition for host tags

  - name: push rcrc
    template: >
      src=rcrc.j2
      dest="{{ unix_admin.home}}/.rcrc"
      mode=0644
      backup=yes

  - name: Install profile
    command: rcup -v -d {{ dotfiles.destination}} {{ dotfiles.rcup_flags }}
    when: dotfiles is defined

  become: yes
  become_user: "{{ unix_admin.name }}"

# - name: correct ownership of ssh config
#   command: chmod 600 {{ user.home }}/.ssh/config
