---

- name: ensure pamac is installed
  pacman: name=pamac state=present

- lineinfile:
    path: /etc/sudoers.d/10-unix_admin
    line: "'{{ unix_admin.name }}' ALL=(ALL) NOPASSWD: ALL"
    create: yes
    validate: 'visudo -cf %s'
  tags: [user]

- name: push pamac conf with aur enabled
  template: >
    src=pamac.conf.j2
    dest=/etc/pamac.conf
    mode=0644
    owner=0
    group=0
    backup=yes
  tags: [package_manager]
  # when: os = arch

- name: Run the equivalent of "pacman -Syu" as a separate step
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags: [package_manager]
  # when: os = arch
