---

- name: ensure pamac is installed
  pacman: name={{ item }} state=present
  with_items:
    - pacaur
    - octopi
  tags: [pkg_mgmt]

- lineinfile:
    path: /etc/sudoers.d/10-unix_admin
    line: "{{ unix_admin.name }} ALL=(ALL) NOPASSWD: ALL"
    create: yes
    validate: 'visudo -cf %s'
  tags: [user]

- name: push pamac conf with aur enabled
  template: >
    src=pamac.conf.j2
    dest=/etc/pamac.conf
    mode=0644
    owner=0
    group=0
    backup=yes
  tags: [package_manager]
  # when: os = arch

- name: push pacaur
  template: >
    src=pacaur.j2
    dest=/etc/xdg/pacaur/config
    mode=0644
    owner=0
    group=0
    backup=yes
  tags: [pacaur]

- name: update using pacaur
  shell: "pacaur --noconfirm -Sc && pacaur -Syu"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: [pacaur]
