---

# - name: New user for AUR management
#   user:
#     name: "{{ unix_admin.name }}"
#     comment: "AUR manager"
#     shell: /bin/nologin
#     home: /var/lib/aurman
#     system: yes
#   tags: [package_manager]
#
# - lineinfile:
#     path: /etc/sudoers.d/11-install-aur_builder
#     line: '"{{ unix_admin.name }}" ALL=(ALL) NOPASSWD: /usr/bin/pacman'
#     create: yes
#     validate: 'visudo -cf %s'
#   tags: [package_manager]


- lineinfile:
    path: /etc/sudoers.d/10-unix_admin
    line: "'{{ unix_admin.name }}' ALL=(ALL) NOPASSWD: ALL"
    create: yes
    validate: 'visudo -cf %s'
  tags: [user]

- name: push pamac conf with aur enabled
  template: >
    src=pamac.conf.j2
    dest=/etc/pamac.conf
    mode=0644
    owner=0
    group=0
    backup=yes
  tags: [package_manager]
  # when: os = arch

- name: Run the equivalent of "pacman -Syu" as a separate step
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags: [package_manager]
  # when: os = arch
