---
#TODO: add check to make sure any local changes aren't lost
- block:

  - name: install dotfiles by tag
    command: rcup -vf -t {{ item }} -x rcrc -x .gitignore
    with_items: "{{ rcm_tags }}"
    when: isayso == True
    tags: ['rcm']

  become: yes
  become_user: "{{ sudoname }}"
