---

- name: install atom
  shell: "pacaur -S --noedit --noconfirm --needed {{item}}"
  with_items:
    - atom
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: [workstation,packages,atom]

#TODO: this appears to install (or reinstall) the package regardless
# if it already exists.
- name: install plugins
  command: apm install {{ item }}
  become: yes
  become_user: '{{ unix_admin.name }}'
  with_items:
    - ruby-block
    - atom-beautify
    - blocky
    - language-docker
    - language-dotfiles
    - language-sfz
    - language-ansible
    - highlight-colors
    - color-picker
    - file-types
    - open-terminal-here
    - toolbar
    - ansible-snippets
  tags: [workstation,packages,atom]

#TODO: push atom config.cson and styles.css from rcm
