---
#TODO: make it so the package name is a variable
# - name: Install
#   dnf: >
#     name='https://github.com/atom/atom/releases/download/v1.27.0-beta1/atom.x86_64.rpm'
#     state=present
#   tags: ['atom']


# - name: install plugins
#   command: apm-beta install sb-atom-sonic-pi tool-bar hey-pane language-ansible ABC-notation
#   become: yes
#   become_user: '{{ user.name }}'
#   tags: ['atom']

- name: install atom
  package:
    name: atom
    state: present
    use: '{{ package_manager }}'

- name: install plugins
  command: apm install ruby-block
  become: yes
  become_user: '{{ unix_admin.name }}'
