---

- name: install atom
  package:
    name: atom
    state: present
    use: '{{ package_manager }}'


#TODO: this appears to install (or reinstall) the package regardless
# if it already exists.
- name: install plugins
  command: apm install {{ item }}
  become: yes
  become_user: '{{ unix_admin.name }}'
  with_items:
    - ruby-block
    - atom-beautify
    - blocky
    - language-docker
    - language-dotfiles
    - language-sfz
    - language-ansible
    - highlight-colors
    - color-picker
    - file-types
    - open-terminal-here
    - toolbar
    - ansible-snippets

#TODO: push atom config.cson and styles.css from rcm
