---

- name: install IDE packages
  aur:
    use: pacaur
    name: "{{ atom_pkgs }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['packages']

#TODO: this appears to install (or reinstall) the package regardless
# if it already exists.
- name: install plugins
  command: apm install "{{ item }}"
  with_items: "{{ apm_pkgs }}"
  become: yes
  become_user: '{{ unix_admin.name }}'
  tags: [workstation,packages,atom]
  when: apm_pkgs is defined
