---

- name: install IDE packages
  aur:
    use: yay
    name: "{{ editor_pkgs }}"
    state: present
  become: True
  become_user: "{{ user.name }}"
  tags: ['editor_pkgs']

- name: install plugins
  command: apm install "{{ item }}"
  with_items: "{{ apm_pkgs }}"
  become: yes
  become_user: '"{{ user.name }}"'
  tags: ['apm_pkgs']
  when: install_apm_pkgs == True
