---

- name: install IDE packages
  aur:
    use: yay
    name: "{{ editor_pkgs }}"
    state: present
  become: True
  become_user: "{{ sudoname }}"
  tags: ['editor_pkgs']

#TODO: this appears to install (or reinstall) the package regardless
# if it already exists.
- name: install plugins
  command: apm install "{{ item }}"
  with_items: "{{ apm_pkgs }}"
  become: yes
  become_user: '"{{ sudoname }}"'
  tags: ['apm_pkgs']
  when: apm_pkgs is defined
