---

- include: atom.yml
  tags: ['atom']
  when: workstation == true

- include: rvm.yml
  tags: ['rvm']
  when: workstation == true

# - include: browsers.yml
#   tags: ['browsers']
#
# - include: comm.yml
#   tags: ['communication']
#
# - include: media.yml
#   tags: ['media']
#
# - include: zim.yml
#   tags: ['zim']
