---

- include: atom.yml
  tags: ['atom']
  when: workstation == true

- include: rvm.yml
  tags: ['rvm']
  when: use_rvm == true

# - include: utils.yml
#   tags: ['utils']

# - include: zim.yml
#   tags: ['zim']

- include: browsers.yml
  tags: ['browsers']
#
# - include: comm.yml
#   tags: ['communication']
#
# - include: media.yml
#   tags: ['media']
#
