---

- include: editors.yml
  tags: ['editors']
  when: workstation == true

- include: media.yml
  tags: ['media']

- include: browsers.yml
  tags: ['browsers']

- include: rvm.yml
  tags: ['rvm']
  when: use_rvm == true

- include: printer.yml
  tags: ['printer']
