---

- name: install workstation packages
  shell: "pamac install --no-confirm {{item}}"
  with_items:
    - "{{ workstation_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['workstation_pkgs']

- include: apm.yml
  tags: ['atom', 'apm']

- include: media.yml
  tags: ['media']
  when: install_media_pkgs is defined

- include: printer.yml
  tags: ['printer']
  when: printers is defined
