---

- name: install codecs
  package: name={{ item }} state=present use="{{ package_manager }}"
  with_items:
    - amrnb
    - amrwb
    - faac
    - faad2
    - flac
    - lame
    - libdca
    - libmad
    - libmatroska
    - x264
    - x265
    - xvidcore
    - ffmpeg
    - ffmpeg-libs
    - ffmpeg-devel
  when: rpmfusionst.stat.exists

# maybe: https://github.com/mps-youtube/mps-youtube

# - name: install mpv
#   package: name=mpv state=present
#   tags: ['video', 'mpv']

- name: install vlc
  package: name=vlc state=present
  tags: ['video', 'vlc']

- name: install youtube-dl
  package: name=youtube-dl state=present
  tags: ['youtube-dl']

- name: install transmission-cli
  package: name=transmission-cli state=present
  tags: ['transmission-cli']
