---

- name: push bluray decoder thingy
  copy:
    src: config/aacs
    dest: "{{ unix_admin.home }}/.config/aacs"
    directory_mode: yes
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['bluray']

- name: install these packages
  aur:
    use: pacaur
    name: {{ media_pkgs }}
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['packages']
