---

- name: Create a directory if it does not exist
  file:
    path: "{{ unix_admin.home }}/.config/aacs"
    state: directory
    owner: "{{ unix_admin.name }}"
    group: "{{ unix_admin.primary_group }}"
    mode: '0755'
  tags: ['bluray']

- block:

  - name: push bluray decoder thingy
    copy:
      src: config/aacs/KEYDB.cfg
      dest: "{{ unix_admin.home }}/.config/aacs/KEYDB.cfg"
    tags: ['bluray']

  - name: install these packages
    aur:
      use: pacaur
      name: "{{ media_pkgs }}"
      state: present
    tags: ['packages']

  become: True
  become_user: "{{ unix_admin.name }}"

- name: push mpv image viewer script
  copy:
    src: usr/share/mpv/scripts/image.lua
    dest: /usr/share/mpv/scripts/image.lua
    directory_mode: no
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ['mpv']
