---

- name: install audacity
  package:
    name: "{{ item }}"
    state: present
    use: '{{ package_manager }}'
  with_items:
    - audacity

- name: install reaper,sws and ocenaudio
  aur:
    use: yay
    name:
      - ocenaudio
      - reaper-bin
      - sws
  become: yes
  become_user: aur_builder
  tags: ['aur']
