---

- name: install deadbeef
  aur: name= {{ item }} user=aurman
  with_items:
    - deadbeef-jack-git
    - deadbeef-plugin-customizabletb-gtk3-git
    - deadbeef-plugin-headerbar-gtk3-git
    - deadbeef-plugin-medialib-git
    - deadbeef-plugin-musical-spectrum-gtk3-git
    - deadbeef-plugin-spectrogram-gtk3-git
    - deadbeef-plugin-waveform-gtk3-git
  tags: [studio,deadbeef]
