---

- name: install audio packages
  package:
    name: "{{ item }}"
    state: present
    use: '{{ package_manager }}'
  with_items:
    - jack2
    - a2jmidid
    - zita-ajbridge
    - realtime-privileges
    - njconnect
    - patchage
    - jacktrip
    - jaaa
    - japa
    - non-mixer
    - non-sequencer
    - carla
    - lv2
    - alsa-card-profiles
    - alsa-firmware
    - alsa-lib
    - alsa-plugins
    - alsa-tools
    - alsa-topology-conf
    - alsa-ucm-conf
    - alsa-utils
    - zita-alsa-pcmi
    - jack_capture
    - sox
  tags: [studio,audio]

- name: install visual packages
  package:
    name: {{ item }}
    state: present
    use: {{ package_manager }}
  with_items:
    - gpick
  tags: [studio,visual]

- name: install audio tools from aur
  aur: name= {{ item }} user=aurman
  with_items:
    - raysession-git
    - jalv-select
    - jack-keyboard
    - ffmulticonverter
    - googler
    - mpv-plugin-excerpt-git
    - reaper-bin
    - sws
    - scala-music
    - scala-music-scales
    - unsilence
  tags: [studio,audio]

- include: deadbeef.yml
  tags: ['deadbeef']

- include: daw.yml
  tags: ['daw']

- name: add user to audio and jackuser group
  user: name={{ user.name }} groups=realtime append=yes
  tags: ['realtime']

- include: plugins.yml
  tags: ['plugins']

- include: sonicpi.yml
  tags: ['sonicpi']
#

#
# - include: utils.yml
#   tags: ['audio_tools']


#include: zita.yml
#ptags: ['zita']

#- include: linuxsampler.yml
#  tags: ['linuxsampler']

# - include: effects.yml
#   tags: ['effects']
#
# - include: score.yml
#   tags: ['abc']
#
# - include: synth.yml
#   tags: ['synth']
#

#
# - include: realtime.yml
#   tags: ['realtime']

# - name: install these thingsuse="{{ package_manager }}"
#   package: name={{ item }} state=present use="{{ package_manager }}"
#   with_items:
#     - guitarix
#     - hydrogen
#     - non-sequencer
#     - qmidiarp
#     - qsynth
#     - rakarrack
#     - sooperlooper
#     - vmpk
#     - zynaddsubfx
#     - lv2-swh-plugins
#     - python3-rdflib
#     - mixxx
#   tags: ['core']
