---
- name: install studio packages
  shell: "pamac install --no-confirm {{item}}"
  with_items:
    - "{{ studio_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['studio_pkgs']

- include: pulse.yml
  tags: ['pulse']

#TODO: medailib plugin fails during build
- include: deadbeef.yml
  ignore_errors: yes
  tags: ['deadbeef']

- include: daw.yml
  ignore_errors: yes
  tags: ['daw']

- include: plugins.yml
  tags: ['plugins']

- include: utils.yml
  tags: ['audio_tools']

- include: synth.yml
  tags: ['synth']

- include: sonicpi.yml
  tags: ['sonicpi']
