---

- name: install audio packages
  package:
    name: "{{ item }}"
    state: present
    use: '{{ package_manager }}'
  with_items:
    - jack2
    - a2jmidid
    - zita-ajbridge
    - realtime-privileges
    - njconnect
    - patchage
    - jacktrip
    - non-sequencer
    - carla
    - lv2
    - alsa-card-profiles
    - alsa-firmware
    - alsa-lib
    - alsa-plugins
    - alsa-tools
    - alsa-topology-conf
    - alsa-ucm-conf
    - alsa-utils
    - zita-alsa-pcmi
    - jack_capture
    - sox
    - mixxx
    - sooperlooper
  tags: [studio,audio]

- name: install visual packages
  package:
    name: "{{ item }}"
    state: present
    use: "{{ package_manager }}"
  with_items:
    - gpick
  tags: [studio,visual]

- name: install audio tools from aur
  aur: name= {{ item }} user=aurman
  with_items:
    - studio-controls-git
    - raysession-git
    - jalv-select
    - jack-keyboard
    - ffmulticonverter
    - googler
    - mpv-plugin-excerpt-git
    - reaper-bin
    - sws
    - scala-music
    - scala-music-scales
    - unsilence
  tags: [studio,audio]

- include: deadbeef.yml
  tags: ['deadbeef']

- include: daw.yml
  tags: ['daw']

- name: add user to audio and jackuser group
  user: name={{ unix_admin.name }} groups=realtime append=yes
  tags: ['realtime']

- include: plugins.yml
  tags: ['plugins']

- include: sonicpi.yml
  tags: ['sonicpi']

- include: utils.yml
  tags: ['audio_tools']

- include: synth.yml
  tags: ['synth']

#include: zita.yml
#ptags: ['zita']

#- include: linuxsampler.yml
#  tags: ['linuxsampler']

# - include: effects.yml
#   tags: ['effects']
#
# - include: score.yml
#   tags: ['abc']
#
