---

- name: install audio packages
  shell: "pacaur -S --noedit --noconfirm --needed {{item}}"
  with_items:
    - jack2
    - a2jmidid
    - zita-ajbridge
    - realtime-privileges
    - njconnect
    - patchage
    - jacktrip
    - carla
    - lv2
    - alsa-card-profiles
    - alsa-firmware
    - alsa-lib
    - alsa-plugins
    - alsa-tools
    - alsa-topology-conf
    - alsa-ucm-conf
    - alsa-utils
    - zita-alsa-pcmi
    - jack_capture
    - sox
    - mixxx
    - polyphone
    # - studio-controls-git
    # - raysession-git
    - jalv-select
    - jack-keyboard
    - ffmulticonverter
    - scala-music
    # - scala-music-scales
    - unsilence
    - sooperlooper
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'Total Installed Size' in command_result.stdout"
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: [studio,packages,audio]

- name: install visual packages
  shell: "pacaur -S --noedit --noconfirm --needed {{item}}"
  with_items:
    - gpick
    - mpv-plugin-excerpt-git
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'Total Installed Size' in command_result.stdout"
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: [studio,packages,visual]

- name: push autojack service file
  copy:
    src: usr/lib/systemd/user/studio.service
    dest: /usr/lib/systemd/user/studio.service
    directory_mode: no
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: [autojack]

- include: deadbeef.yml
  tags: ['deadbeef']

- include: daw.yml
  tags: ['daw']

- name: Get list of groups
  shell: /usr/bin/getent group | awk -F":" '{print $1}'
  register: etc_groups
  tags: [debug]

- name: print etc_groups
  ansible.builtin.debug:
    var: etc_groups
  tags: [debug]

#TODO:conditioal does not work
# - name: add user to audio and jackuser group
#   user: name="{{ unix_admin.name }}" groups=realtime append=yes
#   when: realtime in etc_groups.stdout_lines
#   tags: ['realtime']

- include: plugins.yml
  tags: ['plugins']

- include: utils.yml
  tags: ['audio_tools']

- include: synth.yml
  tags: ['synth']

#include: zita.yml
#ptags: ['zita']

#- include: linuxsampler.yml
#  tags: ['linuxsampler']

# - include: effects.yml
#   tags: ['effects']
#
# - include: score.yml
#   tags: ['abc']
#
