---

- name: install lv2,ladspa & vst plugins
  shell: "pacaur -S --noedit --noconfirm --needed {{item}}"
  with_items:
    - ladspa
    - swh-plugins
    - lv2
    - x42-plugins
    - sfizz
    - iempluginsuite
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'Total Installed Size' in command_result.stdout"
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: [studio,plugins]
