---

- name: install pulseaudio stuffs in another universe where i need it
  package: name={{ item }} state=absent
  with_items:
    - alsa-plugins-pulseaudio
    - pulseaudio-utils
    - pulseaudio-module-jack
    - pulseaudio
    - pavucontrol
