---

- name: install sonic-pi
  aur:
    use: yay
    name: "{{ sonic_pkgs }}"
    state: present
  become: True
  become_user: "{{ user.name }}"
  tags: ['studio_pkgs']

- name: check if sonic-pi-tool is installed
  stat: path="{{ user.home }}/.cargo/bin/sonic-pi-tool"
  register: hassonictool

- name: install sonic-pi tool
  shell: cargo install --git https://github.com/syncopatedstudios/sonic-pi-tool.git --force
  args:
    executable: /bin/bash
  become: True
  become_user: "{{ user.name }}"
  when: not hassonictool.stat.exists
  tags: ['sonicpitool']
