---

- name: install
  shell: "pacaur -S --noedit --noconfirm --needed {{ item }}"
  with_items:
    - wkhtmltopdf-static
    - sonic-pi
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: install sonic-pi tool
  shell: cargo install --git https://github.com/syncopatedstudios/sonic-pi-tool.git --force
  args:
    executable: /bin/bash
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"
  ignore_errors: False
  tags: ['sonicpitool']
