---

- name: install build dependencies
  package: name={{ item }} state=present use="{{ package_manager }}"
  with_items:
    - boost
    - cmake
    - git
    - erlang-nox
    - gendesk
    - lua
    - qt5-tools
    - rtmidi
  tags: ['sonicpi']

- aur:
    use: yay
    name:
      - wkhtmltopdf-static
  become: yes
  become_user: aur_builder
  tags: ['sonicpi']

- name: install runtime dependencies
  package: name={{ item }} state=present use="{{ package_manager }}"
  with_items:
    - aubio
    - gcc-libs
    - glibc
    - osmid
    - qt5-base
    - qscintilla-qt5
    - ruby
    - ruby-activesupport
    - ruby-bundler
    - ruby-ffi
    - ruby-i18n
    - ruby-kramdown
    - ruby-minitest
    - ruby-mocha
    - ruby-multi_json
    - ruby-rake
    - ruby-rouge
    - ruby-rugged
    - ruby-sys-proctable
    - sc3-plugins
    - sox
    - supercollider
  tags: ['sonicpi']


#TODO conditional to check if sonic-pi-tool already exists. if it does, ansible fartsx.

# - name: install sonic-pi-tool prereqs
#   package: name="cargo" state="present"
#   tags: ['sonic']
#
# - name: install sonic-pi-tool
#   command: "cargo install --git https://github.com/lpil/sonic-pi-tool/"
#   become: yes
#   become_user: "{{ user.name }}"
#   tags: ['sonic']

#
- name: clone sonic pi
  git: >
    repo=https://github.com/samaaron/sonic-pi.git
    dest="{{ unix_admin.home }}/Workspace/sonic-pi"
    accept_hostkey=yes
    update=no
    force=no
  become: yes
  become_user: "{{ user.name }}"
  tags: ['sonicpi']
