---

- name: install sonic-pi
  aur:
    use: pacaur
    name: "{{ sonic_pkgs }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['packages']

- name: install sonic-pi tool
  shell: cargo install --git https://github.com/syncopatedstudios/sonic-pi-tool.git --force
  args:
    executable: /bin/bash
  become: True
  become_user: "{{ unix_admin.name }}"
  ignore_errors: False
  tags: ['sonicpitool']
