---

- name: install synths
  package: name={{ item }} state=present use="{{ package_manager }}"
  with_items:
    - helm-synth
    - zynaddsubfx
  tags: ['synth']

- name: install sequencers and samplers
  package: name={{ item }} state=present use="{{ package_manager }}"
  with_items:
    - qmidiarp
    - non-sequencer
    - qsampler
    - jsampler
  tags: ['sequencers']

- name: install hydrogen and flac drumkits
  aur: name= {{ item }} user="{{ unix_admin.name }}"
  with_items:
    - hydrogen-git
    - hydrogen-drumkits-flac
  tags: [hydrogen,sequencers]

- name: install konfyt
  aur: name= {{ item }} user="{{ unix_admin.name }}"
  with_items:
    - konfyt
  tags: ['samplers']
