---

- block:

  - name: create directory folder if it doesn't already exist
    file:
      path: "{{ themes_dir }}"
      state: directory
      mode: 0744
      owner: "{{ unix_admin.gid }}"
      group: "{{ unix_admin.gid }}"

  - name: push theme
    copy: >
      src=themes/oomox-equilibrium-gray-dark.tar.gz
      dest="{{ temp_dir }}"
      owner="{{ unix_admin.uid }}"
      group="{{ unix_admin.gid }}"

  - name: extract tarball
    command: "tar -xf oomox-equilibrium-gray-dark.tar.gz -C '{{ themes_dir }}'"
    args:
      chdir: "{{ temp_dir }}"

  - name: create directory folder if it doesn't already exist
    file:
      path: "{{ icons_dir }}"
      state: directory
      mode: 0744
      owner: "{{ unix_admin.gid }}"
      group: "{{ unix_admin.gid }}"

  - name: push icons
    copy:
      src: icons/oomox-equilibrium-gray-dark-icons.tar.gz
      dest: "{{ temp_dir }}"
      directory_mode: no

  - name: extract tarball
    command: "tar -xf oomox-equilibrium-gray-dark-icons.tar.gz -C '{{ icons_dir }}'"
    args:
      chdir: "{{ temp_dir }}"

  become: yes
  become_user: "{{ sudoname }}"

- name: push background
  copy:
    src: usr/share/backgrounds/
    dest: /usr/share/backgrounds/
    directory_mode: yes
    mode: 0644
  tags: ['backgrounds']
