---

#- name: clone nerd-fonts
#  git: >
#    repo=https://github.com/ryanoasis/nerd-fonts.git
#    dest="{{ local_src_dir }}/nerd-fonts"
#    accept_hostkey=yes
#    clone=yes
#    update=yes
#    force=yes
#  become: yes
#  become_user: "{{ user.name }}"

# ignore errors here. the fonts get copied,
# ansible just complains because it cant
# update the system fontcache

# "shell"
#   "prefix": "shell"
#   "body": """
#     - name: install $1
#       shell: $2"<scriptname.sh> --arg"
#       args:
#         chdir: $3"<working directory>"
#         executable: /bin/bash
#       become: yes
#       become_user: "{{ unix_admin.name }}"
#       ignore_errors: True


- name: install fonts
  shell: "yes | pamac install {{item}}"
  with_items:
    - ttf-hack
    - ttf-font-awesome
    - ttf-devicons
    - ttf-input
    - otf-font-awesome-5-free
    - nerd-fonts-iosevka
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  become: true
  become_user: "{{ansible_env.USER}}"
  tags: [fonts]

#- name: install japanese lang support
#  package: name={{ item }} state=present use="{{ package_manager }}"
#  with_items:
#    - langpacks-ja
#    - vlgothic-fonts

#- name: install hindi lang support
#  package: name={{ item }} state=present use="{{ package_manager }}"
#  with_items:
#   - langpacks-hi
#   - sarai-fonts

#- name: install russian lang support
#  package: name={{ item }} state=present use="{{ package_manager }}"
#  with_items:
#   - langpacks-ru
#   - fonts-KOI8-R
