---

- include: sway.yml
  tags: ['ui','sway']

- include: themes.yml
  tags: ['themes']

- include: fonts.yml
  tags: ['fonts']

- include: desktop.yml
  tags: ['desktop']

- include: search.yml
  tags: ['search']

- name: install themes
  aur:
    use: yay
    name: "{{ theme_pkgs }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['theme_pkgs']

- name: install ui_pkgs
  aur:
    use: yay
    name: "{{ ui_pkgs }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['ui_pkgs']
