---

- name: install theme packages
  shell: "pamac install --no-confirm {{ item }}"
  with_items:
    - "{{ theme_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['theme_pkgs']

- include: sway.yml
  tags: ['ui','sway']

- include: ui_pkgs.yml
  tags: ['ui_pkgs']

- include: tuigreet.yml
  tags: ['tuigreet']
  when: tuigreet == true

- include: gtkgreet.yml
  tags: ['gtkgreet']
  when: gtkgreet == true

#TODO: put these in image or package or add another conditional....
# - include: custom_themes.yml
#   tags: ['oomox']

#https://docs.ansible.com/ansible/2.4/playbooks_loops.html#nested-loops
