---

- include: sway.yml
  tags: ['ui','sway']

- include: ui_pkgs.yml
  tags: ['ui_pkgs']

- include: desktop.yml
  tags: ['desktop']

- include: search.yml
  tags: ['search']

- include: tuigreet.yml
  tags: ['tuigreet']
  when: tuigreet == True

- include: gtkgreet.yml
  tags: ['gtkgreet']
  when: gtkgreet == True

- include: custom_themes.yml
  tags: ['oomox']

- include: mako.yml
  tags: ['mako']
