---

- include: sway.yml
  tags: ['ui','sway']

- include: fonts.yml
  tags: ['fonts']

- include: desktop.yml
  tags: ['desktop']

- name: install themes
  aur:
    use: pacaur
    name: "{{ theme_pkgs }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['theme_pkgs']
