---

- include: sway.yml
  tags: ['ui','sway']

- include: fonts.yml
  tags: ['fonts']

- name: install some utils
  shell: "pacaur -S --noedit --noconfirm --needed {{item}}"
  with_items:
    - oomox
    - keyboardlayouteditor-git
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  become: True
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: [ui,packages,utils]
  when: pkgutils == true
