---

- name: install essential packages
  shell: "pacaur -S --noedit --noconfirm --needed {{item}}"
  with_items:
    - arch-wiki-man
    - surfraw
    - most #for viewing man pages in color
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'Total Installed Size' in command_result.stdout"
  become: true
  become_user: "{{ansible_env.SUDO_USER}}"
