---

- name: install sway stuff
  shell: "pamac install --no-confirm {{item}}"
  with_items:
    - "{{ sway_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['sway_pkgs']

- name: create directory folder if it doesn't already exist
  file:
    path: /etc/sway
    state: directory
    mode: 0755
    owner: root
    group: root
  tags: ['sway_etc']

- name: push sway etc dir
  synchronize:
    src: etc/sway
    dest: /etc/
    recursive: yes
    mode: push
    delete: yes
  tags: ['sway_etc']

- name: push sway share dir
  synchronize:
    src: usr/share/sway
    dest: /usr/share/
    recursive: yes
    mode: push
    delete: yes
  tags: ['sway_usr']

- name: push xdg autostart dir with disabled items
  synchronize:
    src: etc/skel/.config/autostart/
    dest: "{{ user.home }}/.config/autostart/"
    recursive: yes
    mode: push
    delete: yes
  tags: ['autostart']

- name: push systemd user services
  synchronize:
    src: etc/skel/.config/systemd/user/
    dest: "{{ user.home }}/.config/systemd/user/"
    recursive: yes
    mode: push
    delete: no
  notify: reload user systemd
  tags: ['autostart']

#TODO: enable services after sway-session.service is sorted
