---


# this will probably be redudant as this should be included with
# in the base installation

- name: install sway
  package: >
    name = '{{ item }}'
    state = present
    use = '{{ package_manager }}'
  with_items:
    - waybar
    - swayidle

- name: install sway stuff from aur
  aur: name={{ item }} user={{ unix_admin.name }}
  with_items:
    - sway
    - wofi
    - azote
    - swayout
    - swaylock-blur-bin
    - wlogout
    - gtk3-nocsd-git
    - greetd
    - greetd-tuigreet
  tags: ['swaypkgs']

- name: push system env variables to profile.d directory
  copy:
    src: etc/profile.d/
    dest: /etc/profile.d/
    directory_mode: yes
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ['profiled']

#- name: push global sway configs
#  copy:
#    src: etc/sway/
#    dest: /etc/sway/
#    directory_mode: yes
#    owner: root
#    group: root
#    mode: '0644'
#    backup: yes
#  tags: ['sway']

- name: push greetd configs
  copy:
    src: etc/greetd/
    dest: /etc/greetd/
    directory_mode: yes
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ['greetd']

- name: enable greetd service
  systemd: enabled=yes state=started name=greetd
  tags: ['greetd']
