---

- name: install sway stuffs
  aur:
    use: yay
    name: "{{ sway_pkgs }}"
    state: present
  become: True
  become_user: "{{ sudoname }}"
  tags: ['sway_pkgs']

- name: create directory folder if it doesn't already exist
  file:
    path: /etc/sway
    state: directory
    mode: 0755
    owner: root
    group: root
  tags: ['sway_etc']

- name: push main sway dir to etc
  synchronize:
    src: etc/sway
    dest: /etc/
    recursive: yes
    mode: push
    delete: yes
  tags: ['sway_etc']

# - name: create sway config dir
#   file:
#     path: ~/.config/sway/
#     state: directory
#
# - name: copy configuration file
#   template:
#     src: config.j2
#     dest: ~/.config/sway/config
#
# - name: copy gsettings importer
#   copy:
#     src: import-gsettings
#     dest: ~/.config/sway/
#     mode: 0755
#
# - name: copy config user.dirs
#   copy:
#     src: user-dirs.dirs
#     dest: ~/.config/
