---


# this will probably be redudant as this should be included with
# in the base installation

- name: install essential packages
  shell: "pacaur -S --noedit --noconfirm --needed {{item}}"
  with_items:
    - waybar
    - swayidle
    - sway
    - wofi
    - azote
    - swayout
    - swaylock-blur-bin
      #    - wlogout # having an issue checking package key
    - gtk3-nocsd-git
    - greetd
    - greetd-tuigreet
    - qt5-wayland
    - qt5ct
    - wlrobs
    - pywal-git
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: true
  become_user: "{{ansible_env.SUDO_USER}}"

#- name: push global sway configs
#  copy:
#    src: etc/sway/
#    dest: /etc/sway/
#    directory_mode: yes
#    owner: root
#    group: root
#    mode: '0644'
#    backup: yes
#  tags: ['sway']

# - name: push greetd configs
#   copy:
#     src: etc/greetd/
#     dest: /etc/greetd/
#     directory_mode: yes
#     owner: root
#     group: root
#     mode: '0644'
#     backup: yes
#   tags: ['greetd']

- name: push greetd
  template: >
    src=etc/greetd/config.toml.j2
    dest=/etc/greetd/config.toml
    mode=0644
    owner=0
    group=0
    backup=yes
  tags: [greetd]

- name: enable greetd service
  systemd: enabled=yes name=greetd
  ignore_errors: true
  tags: ['greetd']
