---

- name: ensure aacs dir exists
  file:
    path: "{{ user.home }}/.config/aacs"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.primary_group }}"
    mode: '0755'
  tags: ['bluray']

- block:

  - name: push bluray decoder thingy
    copy:
      src: config/aacs/KEYDB.cfg
      dest: "{{ user.home }}/.config/aacs/KEYDB.cfg"
    tags: ['bluray']

  become: True
  become_user: "{{ user.name }}"
