---

# if ansible facts contain a btrfs filssystem, ensure scrub enabled and start it

- name: enable and/or start btrfs-scrub@-.timer
  systemd: enabled=yes state=started daemon_reload=yes name=btrfs-scrub@-.timer


#ansibel_mounts.fstype include btrfs
