---

# if ansible facts contain a btrfs filssystem, ensure scrub enabled and start it
- name: check if the btrfs filesystem is being used
  set_fact:
    btrfs_exists: true
  loop: "{{ ansible_mounts }}"
  when: "'btrfs' in item.fstype"

- name: enable and/or start btrfs-scrub@-.timer
  systemd: enabled=yes state=started daemon_reload=yes name=btrfs-scrub@-.timer
