---

- name: install docker stuffs
  aur:
    use: pacaur
    name: "{{ docker_pkgs }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['packages']

- name: enable and/or start docker
  systemd: enabled=yes state=started daemon_reload=yes name={{ item }}
  with_items:
    - docker
  tags: [docker,systemd]

- name: add this user to desired groups
  user: >
    name={{ unix_admin.name }}
    groups=docker
    append=yes
    state=present
