---

- name: push default grub file
  template: >
    src=defaultgrub.j2
    dest=/etc/default/grub
    owner=0
    group=0
    mode=0644
    backup=yes
  tags: ['grub']
  register: result

- name: remake grub configs
  command: update-grub
  when: result.changed == True
  tags: ['grub']
