---

# packages to install on any system
- name: install packages
  package:
    name: "{{ item }}"
    state: present
    use: '{{ package_manager }}'
  with_items:
    - timeshift
    - bat
    - terminator
    - htop
    - barrier
    - rofi
    - samba
    - bind
    - zim
    - lsd
    - ranger
    - vim
    - bash-completion
    - privoxy
    - fd
    - autofs

- name: install rcm
  aur: name= {{ item }} user={{ unix_admin.name }}
  with_items:
    - lnav
  tags: [system]
