---

# packages to install on any system
- name: install packages
  package:
    name: "{{ item }}"
    state: present
    use: '{{ package_manager }}'
  with_items:
    - timeshift
    - firefox-bin
    - bat
    - terminator
    - htop
    - barrier
    - rofi
    - samba
    - bind
    - zim
    - lsd
    - ranger
    - vim
    - bash-completion
    - privoxy
    - fd
    - autofs
    - bmenu
