---

- name: install system packages
  shell: "pamac install --no-confirm {{ item }}"
  with_items:
    - "{{ system_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['system_pkgs']
