---

- include: user.yml
  # with_items: "{{ unix_users }}"
  tags: ['accounts,user']
  # when: item != None

- include: pamac.yml
  tags: ['packages']

- include: install.yml
  tags: ['install']

- include: docker.yml
  tags: ['docker']
  when: docker_host == True

- include: autofs.yml
  tags: ['autofs']

- include: autosync.yml
  tags: ['autosync']
  when: portable is defined

- name: push default grub file
  template: >
    src=defaultgrub.j2
    dest=/etc/default/grub
    owner=0
    group=0
    mode=0644
    backup=yes
  tags: ['grub']
  register: result

- name: remake grub configs
  command: update-grub
  when: result.changed == True
  tags: ['grub']

- name: push systemd configs
  copy:
    src: etc/systemd/
    dest: /etc/systemd/
    directory_mode: yes
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ['systemd,logs']
