---

- include: user.yml
  with_items: "{{ unix_users }}"
  tags: [accounts,user]
  when: item != None

- include: pamac.yml
  tags: ['packages']
  when: ansible_distribution == "Archlinux" and ansible_pkg_mgr == "pacman"

- include: install.yml
  tags: ['install']
