---

- include: sudoers.yml
  tags: ['sudoers']
  # when: item != None

- include: pamac.yml
  tags: ['packages']

- include: install.yml
  tags: ['install']

- include: snapper.yml
  tags: ['snapper']
  when: usesnapper is defined

# if ansible facts contain a btrfs filssystem, ensure scrub enabled and start it
- name: check if the btrfs filesystem is being used
  set_fact:
    btrfs_exists: true
  loop: "{{ansible_mounts}}"
  when: "'btrfs' in item.fstype"

- include: btrfs.yml
  tags: ['btrfs']
  when: btrfs_exists

- include: docker.yml
  tags: ['docker']
  when: docker_host == True

- include: autofs.yml
  tags: ['autofs']
  when: autofs is defined

- include: autosync.yml
  tags: ['autosync']
  when: portable is defined

- include: grub.yml
  tags: ['grub']
  when: pi == no

- include: fileshare.yml
  tags: ['fileshare']
  when: file_share is defined
