---

- include: user.yml
  tags: ['user']
  # when: item != None

- include: pamac.yml
  tags: ['packages']

- include: install.yml
  tags: ['install']

- include: snapper.yml
  tags: ['snapper']

# if ansible facts contain a btrfs filssystem, ensure scrub enabled and start it
- name: check if the btrfs filesystem is being used
  set_fact:
    btrfs_exists: true
  loop: "{{ansible_mounts}}"
  when: "'btrfs' in item.fstype"

- include: btrfs.yml
  tags: ['btrfs']
  when: btrfs_exists

- include: docker.yml
  tags: ['docker']
  when: docker_host == True

- include: autofs.yml
  tags: ['autofs']

- include: autosync.yml
  tags: ['autosync']
  when: portable is defined

- name: push default grub file
  template: >
    src=defaultgrub.j2
    dest=/etc/default/grub
    owner=0
    group=0
    mode=0644
    backup=yes
  tags: ['grub']
  register: result

- name: remake grub configs
  command: update-grub
  when: result.changed == True
  tags: ['grub']

- name: push systemd configs
  copy:
    src: etc/systemd/
    dest: /etc/systemd/
    directory_mode: yes
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ['systemd', 'logs']
