---

- include: sudoers.yml
  tags: ['sudoers']
  # when: item != None
- include: pamac.yml
  tags: ['packages']

- include: install.yml
  tags: ['install']

- include: grub.yml
  tags: ['grub']

- include: systemd.yml
  tags: ['logging']

- include: modprobe.yml
  tags: ['modprobe']

- include: docker.yml
  tags: ['docker']
  when: docker_host == True

- include: autofs.yml
  tags: ['autofs']
  when: autofs is defined

- include: autosync.yml
  tags: ['autosync']
  when: portable is defined

- include: fileshare.yml
  tags: ['fileshare']
  when: file_share is defined
