---

- include: user.yml
  with_items: "{{ unix_users }}"
  tags: [accounts,useradd]
  when: item != None

- include: network.yml
  tags: ['network']

- include: pamac.yml
  tags: ['packages']

- include: rpi.yml
  tags: ['packages']
