---
- include: user.yml
  tags: ['users']

- include: sudoers.yml
  tags: ['sudoers']

- include: pamac.yml
  tags: ['packages']

- include: grub.yml
  tags: ['grub']

- include: systemd.yml
  tags: ['systemd']

- include: logging.yml
  tags: ['logging']
  notify: reload systemd

- include: modprobe.yml
  tags: ['modprobe']

- include: docker.yml
  tags: ['docker']
  when: docker_host == True

- include: kvm.yml
  tags: ['kvm']
  when: kvm_host == True

- include: autofs.yml
  tags: ['autofs']
  when: autofs is defined

- include: autosync.yml
  tags: ['autosync']
  when: portable is defined

- include: fileshare.yml
  tags: ['fileshare']
  when: file_share is defined

- include: bluray.yml
  tags: ['bluray']

- include: bluetooth.yml
  tags: ['bluetooth']
