---

- name: clean and update repo db
  command: yay -Sc --noconfirm
  become: yes
  become_user: "{{ user.name }}"

- name: install pamac with aur
  command: yay -S --noconfirm --needed pamac
  become: yes
  become_user: "{{ user.name }}"
  ignore_errors: False
  tags: ['pamac']

- block:
  - name: get list of installed packages
    shell: "pamac list --installed | grep -v AUR | awk '{print $1}'"
    register: installed_arch_pkgs

  - name: get list of installed aur packages
    shell: "pamac list --installed | grep AUR | awk '{print $1}'"
    register: installed_aur_pkgs

  become: yes
  become_user: "{{ user.name }}"
