---

- user:
    name: aur_builder
    group: wheel
- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: push pamac conf with aur enabled
  template: >
    src=pamac.conf.j2
    dest=/etc/pamac.conf
    mode=0644
    owner=0
    group=0
    backup=yes
  # when: os = arch

- name: Run the equivalent of "pacman -Syu" as a separate step
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  # when: os = arch
