---

- name: clone arch package manager plugin
  git: >
    repo=https://github.com/kewlfft/ansible-aur.git
    dest={{ unix_admin.home}}/.ansible/plugins/modules/aur
    accept_hostkey=yes
    clone=yes
    update=yes
    force=yes
  become: yes
  become_user: "{{ unix_admin.name }}"
  tags: ['arch_pkgs']

- name: push pamac conf with aur enabled
  template: >
    src=etc/pamac.conf.j2
    dest=/etc/pamac.conf
    mode=0644
    owner=0
    group=0
    backup=yes
  tags: ['arch_pkgs', 'configs']

- name: push pacaur config
  template: >
    src=etc/xdg/pacaur.j2
    dest=/etc/xdg/pacaur/config
    mode=0644
    owner=0
    group=0
    backup=yes
  tags: ['arch_pkgs', 'configs']

- name: get list of installed packages
  shell: "pacman -Qet | awk '{print $1}'"
  register: installed_packages
  tags: ['arch_pkgs']

- name: install these packagemanagers
  aur:
    use: auto
    name: "{{ packagemanagers }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['arch_pkgs']
