---

- name: install snapper stuff
  aur:
    use: pacaur
    name: "{{ snapper_pkgs }}"
    state: present
  become: True
  become_user: "{{ unix_admin.name }}"
  tags: ['snapper_pkgs']

- name: push snapper configs
  template: >
    src=etc/snapper/configs/config.j2
    dest=/etc/snapper/configs/{{ item.name }}
    mode=0644
    owner=0
    group=0
    backup=yes
  loop: "{{ subvolumes }}"

- name: push updatedb config
  copy:
    src: etc/updatedb.conf
    dest: /etc/updatedb.conf
    directory_mode: no
    owner: root
    group: root
    mode: '0644'
    backup: yes
