---

- name: check if file and/or directory exists
  stat: "path=/etc/sudoers.d/10-unix_admin"
  register: hazifile
  tags: ['sudoers']

- name: add user to sudoers
  lineinfile:
    path: /etc/sudoers.d/10-user_admin
    line: '"{{ user.name }}" ALL=(ALL) NOPASSWD: ALL'
    create: yes
    validate: 'visudo -cf %s'
  when: not hazifile.stat.exists
  tags: ['sudoers']

- name: ensure rules.d directory exists
  file:
    path: "/etc/polkit-1/rules.d"
    state: directory
    owner: root
    group: root
    mode: '0750'
  tags: ['polkit']

- name: like sudoers for polkit
  template: >
    src=49-nopasswd_global.rules.j2
    dest=/etc/polkit-1/rules.d/49-nopasswd_global.rules
    owner=0
    group=0
    mode=0644
    backup=no
  tags: ['polkit','sudoers']
