---
#
# add user
# copy .ssh from user@bender:~/.ssh

# - lineinfile:
#     path: /etc/sudoers.d/10-unix_admin
#     line: 'b08x ALL=(ALL) NOPASSWD: ALL'
#     create: yes
#     validate: 'visudo -cf %s'
#   tags: [package_manager]

- name: create needed groups
  group: name={{ item.name }} state=present gid={{ item.gid }}
  with_items: "{{ unix_groups }}"

# - name: add user to remote hosts
#   user: >
#     name={{ unix_admin.name }}
#     uid={{ unix_admin.uid }}
#     group={{ unix_admin.primary_group }}
#     groups={{ unix_admin.secondary_groups }}
#     append=yes
#     shell={{ unix_admin.shell }}
#     comment={{ unix_admin.email }}
#     state=present
#     password={{ unix_admin.password }}
#     update_password=on_create
#   register: newuser_remote

# - hosts: serverB
#   tasks:
#    - name: Copy Remote-To-Remote (from serverA to serverB)
#      synchronize: src={{ user.home }}/.ssh dest={{ user.home }}/.ssh
#      delegate_to: bender
#
#
# ###todo: if arch: network if rpi: netdev
# - name: add user to network group
#   user:
#     name: {{ unix_admin.name }}
#     shell: /bin/bash
#     groups: network
#     append: yes
