---

- name: push resolv.conf
  template: >
   src=etc/resolv.conf.j2
   dest=/etc/resolv.conf
   mode=0644
   owner=0
   group=0
   backup=yes
  tags: ['resolv']

- name: push static ethernet config
  template: >
   src=etc/systemd/network/10-static-ethernet.network.j2
   dest=/etc/systemd/network/10-static-ethernet.network
   mode=0644
   owner=0
   group=0
   backup=yes
  tags: ['networkd']

- name: disable NetworkManager service
  systemd: enabled=no state=stopped name=NetworkManager
  ignore_errors: yes

- name: enable networkd service
  systemd: enabled=yes state=started name=systemd-networkd

#- name: enable resolved service
#  systemd: enabled=no state=stopped daemon_reload=yes name=systemd-resolved
#  tags: ['resolvd']
