---
- name: install soundbot packages
  shell: "pamac install --no-confirm {{item}}"
  with_items:
    - "{{ soundbot_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['soundbot_pkgs']

- name: add user to realtime group
  user: name="{{ user.name }}" groups=realtime append=yes

- include: pulse.yml
  tags: ['pulse']

#TODO: medailib plugin fails during build
- include: deadbeef.yml
  ignore_errors: yes
  tags: ['deadbeef']

# - include: daw.yml
#   ignore_errors: yes
#   tags: ['daw']

- include: sonicpi.yml
  tags: ['sonicpi']

- include: plugins.yml
  tags: ['plugins']

- include: utils.yml
  tags: ['audio_tools']

- include: network.yml
  tags: ['soundbot_net']
  when: soundbot_network
