---

- name: install samplers sequencers and synths
  shell: "pamac install --no-confirm {{item}}"
  with_items:
    - "{{ sss_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['sss_pkgs']
