---

- name: install pipx
  command: pip install pipx
  become: True
  become_user: "{{ user.name }}"
  tags: ['unsilence']

- name: check if file and/or directory exists
  stat: path="{{ user.home }}/.local/bin/unsilence"
  register: haziunsilence

- name: install unsilence
  command: pipx install unsilence
  become: True
  become_user: "{{ user.name }}"
  when: not haziunsilence.stat.exists
  tags: ['unsilence']

- name: push sonic-visualizer suite
  synchronize:
    src: .local/
    dest: "{{ user.home }}/.local/"
    recursive: yes
    mode: push
    delete: no
  become: yes
  become_user: "{{ user.name }}"
  tags: ['sonicvisualizer']

- name: Extract vamp plugins into home dir
  unarchive:
    src: vamp.tar.gz
    dest: "{{ user.home }}"
  become: True
  become_user: "{{ user.name }}"
  tags: ['sonicvisualizer', 'vamp']
