---

- name: push boot cfg to enable pirate audio dac
  template: >
    src=boot.config.j2
    dest=/boot/config.txt
    mode=0644
    owner=0
    group=0
    backup=yes


- name: install python modules for gpio stuff
  package:
    name: '{{ item }}'
    state: present
    use: '{{ package_manager }}'
  with_items:
    - python-rpi.gpio
    - python-spidev
    - python-pip
    - python-pil
    - python-numpy

- name: install python module for lcd display
  pip:
    name: st7789
