---

- name: install common system tools
  shell: "pamac install --no-confirm {{item}}"
  with_items:
    - "{{ common_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['common_pkgs']

- name: install yadm
  get_url:
    url: https://github.com/TheLocehiliosan/yadm/raw/master/yadm
    dest: /usr/local/bin/yadm
    mode: '0755'
  tags: ['yadm']

- name: install googler
  get_url:
    url: https://raw.githubusercontent.com/jarun/googler/v4.3.2/googler
    dest: /usr/local/bin/googler
    mode: '0755'
  tags: ['googler']
