---

- name: install common system tools
  shell: "pamac install --no-confirm {{item}}"
  with_items:
    - "{{ common_pkgs }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'installing' in command_result.stdout"
  become: True
  become_user: "{{ user.name }}"
  tags: ['common_pkgs']

- name: install yadm
  get_url:
    url: https://github.com/TheLocehiliosan/yadm/raw/master/yadm
    dest: /usr/local/bin/yadm
    mode: '0755'
  tags: ['yadm']

- name: install oh-my-zsh for user
  shell: /usr/share/oh-my-zsh/tools/install.sh
  args:
    chdir: "{{ user.home }}"
    executable: /bin/sh
  become: yes
  become_user: "{{ user.name }}"
