---

hostname: bender

make_hard: False

docker_host: True
docker_storage: /var/lib/docker

samba_host: True

file_shares:
  subnets: "{{ ansible.default_ipv4.network }}"
  mounts:
    - /mnt/b08x

autofs:
  host: ninjabot
  mounts:
  - share

sshd_port: 22
sshd_allow_groups: b08x

sysctl_ip_forward: True


# portable:
#   uuid: 5732DF544868E675
#   mountpoint: /mnt/autosync
#   filesystem: ntfs
#   options: users,noauto
#   checks: 0,0
#   idVendor: 0bc2
#   idProduct: ac2d
#   disklabel: mediasync

rcm_tags:
  - vim
