---

hostname: bender

make_hard: False

docker_host: True
docker_storage: /var/lib/docker

samba_host: True
samba_shares:
  - /srv/archive
  - /srv/share

nfs_host:
  enabled: True
  subnets: "{{ ansible.default_ipv4.network }}"

sshd_port: 22
sshd_allow_groups: b08x

sysctl_ip_forward: True

package_manager: community.general.pacman
