---

hostname: bender

primary_net_dev: enp3s0
primary_net_addr: "192.168.41.3"
primary_net_mask: "/24"
primary_net_gateway: "192.168.41.1"

# enp2s0f0:
# enp2s0f1:

docker_host: True
docker_storage: /var/lib/docker

samba_host: True

file_shares:
  subnets: "{{ ansible.default_ipv4.network }}"
  mounts:
    - /mnt/b08x

sysctl_ip_forward: True


# portable:
#   uuid: 5732DF544868E675
#   mountpoint: /mnt/autosync
#   filesystem: ntfs
#   options: users,noauto
#   checks: 0,0
#   idVendor: 0bc2
#   idProduct: ac2d
#   disklabel: mediasync
