---

hostname: lapbot
laptop: true

make_hard: False

docker_host: True
docker_storage: /var/lib/docker

sshd_port: 22
sshd_allow_groups: b08x

sysctl_ip_forward: False

workstation: True

window_manager: sway

autofs:
  host: bender
  shares:
    - b08x

# autofs:
#   host: ninjabot
#   shares:
#     - share

rcm_tags:
  - atom
  - deadbeef
  - hexchat
  - mpv
  - qute
  - ranger
  - soundbot
  - sway
  - terminator
  - vim
  - zim
  - git
