---

hostname: ninjabot

# primary_net_dev: w
primary_net_addr: "192.168.41.4"
primary_net_mask: "/24"
primary_net_gateway: "192.168.41.1"

soundbot_bridge: br0
bridge_interfaces: en*
soundbot_net_addr: "10.40.41.1"
soundbot_net_mask: "/28"

tcp_rmem: "10240 87380 33554432"
tcp_wmem: "10240 87380 33554432"

docker_host: True
docker_storage: /var/lib/docker

kvm_host: True
samba_host: True

# folders to make available
file_share:
  subnet: "{{ ansible.default_ipv4.network }}"
  folders:
    - /mnt/share

# showmount -e autofs.host
autofs:
  host: bender
  shares:
    - b08x
