---

hostname: ninjabot
workstation: True
make_hard: False

host_environment_paths:
  PATH: /home/b08x/.rvm/gems/ruby-2.7.2/bin:/home/b08x/.rvm/gems/ruby-2.7.2@global/bin:/home/b08x/.rvm/rubies/ruby-2.7.2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/b08x/.rvm/bin:/home/b08x/.local/bin:/home/b08x/bin
  GEM_PATH: /home/b08x/.rvm/gems/ruby-2.7.2

rvm1_rubies:
  - 'ruby-2.7.2'

rvm1_install_flags: '--user-install'

rvm1_user: 'b08x'

docker_host: True
docker_storage: /var/lib/docker

kvm_host: True

sshd_port: 22
sshd_allow_groups: b08x

dotfiles:
  url: "git@github.com:b08x/dotfiles"
  branch: main
  destination: "{{ user.home }}/Workspace/dotfiles"
  rcup_flags: -f -t profile -x README.md -x rcrc -x *_bak

samba_host: True

# folders to make available
file_share:
  subnet: "{{ ansible.default_ipv4.network }}"
  folders:
    - /mnt/share

# showmount -e autofs.host
autofs:
  host: bender
  shares:
    - b08x

# Black + DarkGrey
color0:  '#282a36'
color8:  '#686868'
# DarkRed + Red
color1:  '#ff5c57'
color9:  '#ff5c57'
# DarkGreen + Green
color2:  '#5af78e'
color10: '#5af78e'
# DarkYellow + Yellow
color3:  '#f3f99d'
color11: '#f3f99d'
# DarkBlue + Blue
color4:  '#57c7ff'
color12: '#57c7ff'
# DarkMagenta + Magenta
color5:  '#ff6ac1'
color13: '#ff6ac1'
# DarkCyan + Cyan
color6:  '#9aedfe'
color14: '#9aedfe'
# LightGrey + White
color7:  '#eff0eb'
color15: '#f1f1f0'
