---

hostname: ninjabot
workstation: True
make_hard: False

host_environment_paths:
  PATH: /home/b08x/.rvm/gems/ruby-2.7.2/bin:/home/b08x/.rvm/gems/ruby-2.7.2@global/bin:/home/b08x/.rvm/rubies/ruby-2.7.2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/b08x/.rvm/bin:/home/b08x/.local/bin:/home/b08x/bin
  GEM_PATH: /home/b08x/.rvm/gems/ruby-2.7.2

rvm1_rubies:
  - 'ruby-2.7.2'

rvm1_install_flags: '--user-install'

rvm1_user: 'b08x'

docker_host: True
docker_storage: /var/lib/docker

sshd_port: 22
sshd_allow_groups: b08x

dotfiles:
  url: "git@github.com:b08x/dotfiles"
  branch: main
  destination: "{{ unix_admin.home }}/Workspace/dotfiles"
  rcup_flags: -f -t profile -x README.md -x rcrc -x *_bak
