---

hostname: ninjabot

soundbot_ip4_network:
  bridge: br0
  interfaces: en*
  address: "10.40.41.1"

docker_host: True
kvm_host: True
samba_host: True

# folders to make available
file_share:
  subnet: "{{ ansible.default_ipv4.network }}"
  folders:
    - /mnt/share

# showmount -e autofs.host
autofs:
  host: bender
  shares:
    - b08x
