---

hostname: ninjabot
network_interface: enp12s0
ipv4_address: "192.168.41.4"
ipv4_netmask: "/24"
ipv4_gateway: "192.168.41.1"
dns_servers: ["192.168.41.1"]

docker_host: True
docker_storage: /var/lib/docker

kvm_host: True
samba_host: True

# folders to make available
file_share:
  subnet: "{{ ansible.default_ipv4.network }}"
  folders:
    - /mnt/share

# showmount -e autofs.host
autofs:
  host: bender
  shares:
    - b08x
