---

hostname: testbot
workstation: True
sshd_port: 22
sshd_allow_groups: b08x
package_manager: community.general.pacman
use_rvm: False
docker_host: True
docker_storage: /var/lib/docker

sysctl_ip_forward: False

dotfiles:
  url: git@github.com:b08x/dotfiles.git
  branch: Main
  destination: "{{ user.home }}/Workspace/dotfiles"
  rcup_flags: -t profile -x README.md -x .gitignore -x manage.rb
