---

window_manger: sway
pkgutils: false

tuigreet: false
gtkgreet: true

ui_pkgs:
  - pcmanfm
  - pcmanfm-hardlinkcopy
  - xarchiver
  - ripgrep-all
  - arch-wiki-man
  - surfraw
  - most #for viewing man pages in color
  - googler
  - scrot

misc_pkgs:
  - oomox
  - keyboardlayouteditor-git
  - nasa-wallpaper
  - pywal-git

#FIXME: :: Downloaded PKGBUILD (1/1): wlogout
#   1 wlogout                          (Build Files Exist)
# ==> Diffs to show?
# ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
# ==>
# :: (1/1) Parsing SRCINFO: wlogout
#
# :: PGP keys need importing:
#  -> F4FDB18A9937358364B276E9E25D679AF73C6D2F, required by: wlogout
# ==> Import? [Y/n] y
# :: Importing keys with gpg...
# gpg: keyserver receive failed: General error
# problem importing keys

sway_pkgs:
  - waybar
  - swayidle
  - sway
  - wofi
  - azote
  - swayout
  - swaylock-blur-bin
  - gtk3-nocsd-git
  - greetd
  - greetd-tuigreet
  - greetd-gtkgreet-git
  - qt5-wayland
  - qt5ct
  # - wlogout
  - mako
  - wf-recorder
  - grimshot

theme_pkgs:
  - vimix-icon-theme
  - vimix-gtk-themes
  - vimix-cursors
  - nerd-fonts-hack
  - otf-font-awesome
  - ttf-devicons
  - ttf-input
  - nerd-fonts-iosevka
  - ttf-nerd-fonts-symbols
  - nerd-fonts-noto-sans-mono
  - gnu-free-fonts
